@startjson fig2
{
    "formFile":"様式ファイル名(pngなど)",
    "pageSize": "ページサイズ(A4など)",
    "orientation" : "ページ方向(portrait/landscape)",
    "areaList" :
    [
        {
            "areaName": "領域名",
            "docFile": "文書ファイル名(mdなど)",
            "varKeyword": "可変キーワード(yyyy/mm/ddなど)",
            "fontName": "フォント名",
            "fontSize": "フォントサイズ",
            "margen-top": "上マージン(mm)", 
            "margin-left" : "左マージン(mm)",
            "margin-right" : "右マージン(mm)",
            "margin-bottom" : "下マージン(mm)"
        }
    ]
}
@endjson
